const { contains } = require("cypress/types/jquery")

describe('CreateBa', () => {
    it('LOGIN TO TIM GUI', () => {
        cy.visit("https://10-tim.imfint.local")
        cy.contains('Log in').click()
        cy.url().should('include','login')
        cy.get('#username').type('Agent').should('have.value','Agent')
        cy.get('#password').type('pa$$w0rd')
        cy.get('input.btn').click()
        cy.get('h2.ng-binding').should('contain','GUI')
        cy.get('a[href="Providers"]').click()
        cy.url().should('include','Providers')
        cy.get('.action-link').click()
        cy.wait(500)
        cy.get('div.col-xs-6:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > input:nth-child(1)')
        .type('POGO BA ZA TEST')
        cy.get(':nth-child(4) > :nth-child(1) > .col-xs-7 > .form-control')
        .type('NL35RABO0117713678')
        cy.get('div.col-xs-6:nth-child(2) > div:nth-child(4) > div:nth-child(1) > div:nth-child(2)')
        .click()
        //cy.contains('Instituut').click()
        //.select('Instituut')
        //cy.contains('Infomedics TIM GUI').should('include','GUI')
        //expect('Infomedics TIM GUI').to.equal('Infomedics TIM GUI')
        //expect(true).to.equal(true)
    })

    // it ('Create BA POGO ZH', () => {
    //     cy.get('a[href="Providers"]').click()
    //     cy.url().should('include','Providers')
    //     cy.contains('create business Account').click()
    // }
    // )
})